#!/usr/bin/env python3
"""Emit LaTeX macros from ``evaluation.json`` so the report cannot drift.

Every quantitative claim in the prototype report is written as a macro defined
here, generated directly from the measured evaluation output. Re-run
``make evaluate && python scripts/render_report_numbers.py`` and the paper
updates itself. Nothing in the report is typed by hand, so the paper and the
code can never disagree.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from bodhi.config import METRICS_DIR, ROOT  # noqa: E402

OUT = ROOT / "docs" / "report" / "results.tex"


def _pct(x: float, dp: int = 1) -> str:
    return f"{100 * float(x):.{dp}f}\\%"


def _num(x: float, dp: int = 4) -> str:
    return f"{float(x):.{dp}f}"


def _int(x) -> str:
    return f"{int(x):,}".replace(",", "{,}")


def main() -> int:
    path = METRICS_DIR / "evaluation.json"
    if not path.exists():
        print(f"missing {path} - run `make evaluate` first", file=sys.stderr)
        return 1
    m = json.loads(path.read_text())

    ds = m["dataset"]
    layers = m["layers"]
    base = m["baseline"]
    cal = m["calibration"]
    lat = m["latency"]
    ind = m["independence_from_tickets"]
    oot = m.get("out_of_time", {})
    lead = m.get("lead_time", {})

    lines = [
        "% ---------------------------------------------------------------",
        "% AUTO-GENERATED by scripts/render_report_numbers.py - do not edit.",
        "% Source: artifacts/metrics/evaluation.json",
        f"% Generated: {m.get('generated_at', 'unknown')}",
        "% ---------------------------------------------------------------",
        "",
        "% --- dataset ---",
        f"\\newcommand{{\\dsAccounts}}{{{_int(ds['accounts'])}}}",
        f"\\newcommand{{\\dsTransactions}}{{{_int(ds['transactions'])}}}",
        f"\\newcommand{{\\dsMules}}{{{_int(ds['mule_accounts'])}}}",
        f"\\newcommand{{\\dsMuleRate}}{{{_pct(ds['mule_rate'], 2)}}}",
        f"\\newcommand{{\\dsRings}}{{{_int(ds['rings'])}}}",
        f"\\newcommand{{\\dsDays}}{{{_int(ds['n_days'])}}}",
        f"\\newcommand{{\\dsFraudTxn}}{{{_int(ds['fraud_transactions'])}}}",
        f"\\newcommand{{\\dsTickets}}{{{_int(ds['fraud_alerts'])}}}",
        "",
        "% --- per-layer performance ---",
    ]

    macro_names = {
        "XGBoost (L4)": "Xgb",
        "GraphSAGE (L5)": "Sage",
        "TGN (L6)": "Tgn",
        "Intelligence": "Intel",
        "Fused (L7)": "Fused",
    }
    for label, suffix in macro_names.items():
        v = layers[label]
        lines += [
            f"\\newcommand{{\\auc{suffix}}}{{{_num(v['roc_auc'])}}}",
            f"\\newcommand{{\\ap{suffix}}}{{{_num(v['pr_auc'])}}}",
            f"\\newcommand{{\\precOne{suffix}}}{{{_num(v['precision_at_1pct'], 3)}}}",
            f"\\newcommand{{\\recOne{suffix}}}{{{_num(v['recall_at_1pct'], 3)}}}",
        ]

    lines += [
        "",
        "% --- calibration ---",
        f"\\newcommand{{\\brier}}{{{_num(cal['brier'], 5)}}}",
        f"\\newcommand{{\\ece}}{{{_num(cal['ece'], 4)}}}",
        "",
        "% --- rule-engine baseline ---",
        f"\\newcommand{{\\ruleAlerts}}{{{_int(base['alerts'])}}}",
        f"\\newcommand{{\\ruleTP}}{{{_int(base['true_positives'])}}}",
        f"\\newcommand{{\\ruleFP}}{{{_int(base['false_positives'])}}}",
        f"\\newcommand{{\\rulePrecision}}{{{_pct(base['precision'], 2)}}}",
        f"\\newcommand{{\\ruleRecall}}{{{_pct(base['recall'], 1)}}}",
        f"\\newcommand{{\\bodhiAlerts}}{{{_int(base['bodhi_alerts_at_equal_recall'])}}}",
        f"\\newcommand{{\\bodhiTP}}{{{_int(base['bodhi_true_positives_at_equal_recall'])}}}",
        f"\\newcommand{{\\bodhiFP}}{{{_int(base['bodhi_false_positives_at_equal_recall'])}}}",
        f"\\newcommand{{\\bodhiPrecision}}{{{_pct(base['bodhi_precision_at_equal_recall'], 2)}}}",
        f"\\newcommand{{\\fpReduction}}{{{_pct(base['false_positive_reduction'], 2)}}}",
        f"\\newcommand{{\\precUplift}}{{{base['precision_uplift_x']:.0f}$\\times$}}",
        "",
        "% --- latency ---",
        f"\\newcommand{{\\latPfifty}}{{{lat['p50_ms']:.3f}}}",
        f"\\newcommand{{\\latPninetynine}}{{{lat['p99_ms']:.3f}}}",
        f"\\newcommand{{\\throughput}}{{{_int(lat['throughput_per_sec'])}}}",
        "",
        "% --- independence from the government feed ---",
        f"\\newcommand{{\\indepShare}}{{{_pct(ind['share_of_detections_not_in_any_ticket'], 0)}}}",
        f"\\newcommand{{\\indepDetected}}{{{_int(ind['detected_never_reported'])}}}",
        f"\\newcommand{{\\indepRecall}}{{{_pct(ind['recall_on_never_reported_mules'], 1)}}}",
    ]

    if oot:
        lines += [
            "",
            "% --- out-of-time ---",
            f"\\newcommand{{\\ootRings}}{{{_int(oot['late_rings'])}}}",
            f"\\newcommand{{\\ootMules}}{{{_int(oot['late_ring_mules'])}}}",
            f"\\newcommand{{\\ootRecall}}{{{_pct(oot['recall'], 1)}}}",
        ]
    if lead and lead.get("median_lead_hours") is not None:
        lines += [
            "",
            "% --- detection lead time ---",
            f"\\newcommand{{\\leadMedian}}{{{lead['median_lead_hours']:.1f}}}",
            f"\\newcommand{{\\leadSpacing}}{{{lead['cut_spacing_hours']:.0f}}}",
            f"\\newcommand{{\\leadEligible}}{{{_int(lead['mules_with_ticket_and_detection'])}}}",
            f"\\newcommand{{\\leadBeforeShare}}{{{_pct(lead['share_detected_before_ticket'], 0)}}}",
            f"\\newcommand{{\\leadNeverTicketed}}{{{_int(lead['detected_but_never_ticketed'])}}}",
        ]

    # weakest typologies, for the honest-limitations table
    weak = [t for t in m["typology"] if not t["typology"].startswith("role:")][:3]
    for i, t in enumerate(weak, 1):
        name = t["typology"].replace("_", " ").title()
        lines += [
            f"\\newcommand{{\\weakName{'ABC'[i-1]}}}{{{name}}}",
            f"\\newcommand{{\\weakRecall{'ABC'[i-1]}}}{{{_pct(t['recall'], 1)}}}",
        ]

    # decoy false-positive rates
    for row in m["hard_negatives"]:
        key = "".join(w.title() for w in row["population"].split("_"))
        lines += [
            f"\\newcommand{{\\decoy{key}N}}{{{_int(row['n'])}}}",
            f"\\newcommand{{\\decoy{key}FP}}{{{_pct(row['false_positive_rate'], 2)}}}",
        ]

    # organisers' alert-dataset track
    boi_path = METRICS_DIR / "boi_track.json"
    if boi_path.exists():
        bm = json.loads(boi_path.read_text())
        bd, bdep, bleak = bm["dataset"], bm["deployable"], bm["leakage_effect"]
        bcv, bhold = bdep["cv"], bdep["holdout"]
        lines += [
            "",
            "% --- organisers' alert dataset (bodhi/boi) ---",
            f"\\newcommand{{\\boiColumns}}{{{_int(bd['declared_columns'])}}}",
            f"\\newcommand{{\\boiRows}}{{{_int(bd['rows'])}}}",
            f"\\newcommand{{\\boiPositives}}{{{_int(bd['positives'])}}}",
            f"\\newcommand{{\\boiStrategy}}{{\\texttt{{{bdep['selected_strategy'].replace('_', chr(92) + '_')}}}}}",
            f"\\newcommand{{\\boiHoldoutAuc}}{{{_num(bhold['roc_auc'])}}}",
            f"\\newcommand{{\\boiCvAuc}}{{{_num(bcv[bdep['selected_strategy']]['roc_auc'])}}}",
            f"\\newcommand{{\\boiPrClean}}{{{_num(bleak['pr_auc_deployable'], 3)}}}",
            f"\\newcommand{{\\boiPrLeaked}}{{{_num(bleak['pr_auc_with_leakage'], 3)}}}",
            f"\\newcommand{{\\boiLeakMultiple}}{{{bleak['multiple']:.1f}}}",
        ]
        for key, macro in [("bank_finalized", "Bank"), ("bank_plus_engineered", "BankEng"),
                           ("auto_topk", "TopK"), ("all", "All")]:
            if key in bcv:
                lines += [
                    f"\\newcommand{{\\boi{macro}N}}{{{_int(bcv[key]['n_features'])}}}",
                    f"\\newcommand{{\\boi{macro}Auc}}{{{_num(bcv[key]['roc_auc'], 3)}}}",
                    f"\\newcommand{{\\boi{macro}Pr}}{{{_num(bcv[key]['pr_auc'], 3)}}}",
                ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    print(f"Wrote {len(lines)} lines of macros to {OUT}")

    # Copy the figures the report includes.
    figures = ROOT / "artifacts" / "figures"
    if figures.exists():
        dest = OUT.parent / "figures"
        dest.mkdir(exist_ok=True)
        for png in figures.glob("*.png"):
            (dest / png.name).write_bytes(png.read_bytes())
        print(f"Copied {len(list(figures.glob('*.png')))} figures to {dest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
